INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('SOLL', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('IST', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('Kautionsart', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('Kontonummer', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('Bank', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('Bemerkungen', '1');