CREATE TABLE IF NOT EXISTS `KAUTION_FELD` (
  `DAT` int(7) NOT NULL AUTO_INCREMENT,
  `FELD` varchar(50) COLLATE latin1_german2_ci NOT NULL,
  `AKTUELL` enum('0','1') COLLATE latin1_german2_ci NOT NULL,
  PRIMARY KEY (`DAT`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_german2_ci;

INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('SOLL', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('IST', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('Kautionsart', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('Kontonummer', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('Bank', '1');
INSERT INTO KAUTION_FELD (FELD, AKTUELL) VALUES ('Bemerkungen', '1');