@if($entity instanceof \App\Models\Einheiten)
    @include('shared.entities.einheit')
@elseif($entity instanceof \App\Models\Haeuser)
    @include('shared.entities.haus')
@elseif($entity instanceof \App\Models\Objekte)
    @include('shared.entities.objekt')
@elseif($entity instanceof \App\Models\Kaufvertraege)
    @include('shared.entities.kaufvertrag')
@elseif($entity instanceof \App\Models\Mietvertraege)
    @include('shared.entities.mietvertrag')
@elseif($entity instanceof \App\Models\Personen)
    @include('shared.entities.person')
@elseif($entity instanceof \App\Models\Details)
    @include('shared.entities.detail')
@endif