@if($entity instanceof \App\Models\Einheiten)
    @include('shared.entities.einheit')
@elseif($entity instanceof \App\Models\Haeuser)
    @include('shared.entities.haus')
@elseif($entity instanceof \App\Models\Objekte)
    @include('shared.entities.objekt')
@elseif($entity instanceof \App\Models\Kaufvertraege)
    @include('shared.entities.kaufvertrag')
@elseif($entity instanceof \App\Models\Mietvertraege)
    @include('shared.entities.mietvertrag')
@elseif($entity instanceof \App\Models\Person)
    @include('shared.entities.person')
@elseif($entity instanceof \App\Models\Details)
    @include('shared.entities.detail')
@elseif($entity instanceof \App\Models\Auftraege)
    @include('shared.entities.auftrag')
@elseif($entity instanceof \App\Models\Partner)
    @include('shared.entities.partner')
@elseif($entity instanceof \App\Models\Wirtschaftseinheiten)
    @include('shared.entities.wirtschaftseinheit')
@elseif($entity instanceof \App\Models\BaustellenExtern)
    @include('shared.entities.baustelle_extern')
@elseif($entity instanceof \App\Models\Lager)
    @include('shared.entities.lager')
@elseif($entity instanceof \App\Models\JobTitle)
    @include('shared.entities.jobtitel')
@elseif($entity instanceof \App\Models\Job)
    @include('shared.entities.job')
@elseif($entity instanceof \App\Models\Credential)
    @include('shared.entities.login')
@endif