FROM php:7.2-fpm

RUN apt-get update \
    && apt-get install -y \
        libpng-dev \
        libcurl4-openssl-dev \
        libzip-dev \
        unzip \
    && docker-php-ext-install -j$(nproc) bcmath calendar curl gd mysqli pdo_mysql zip opcache \
    && pecl install xdebug-2.6.1 \
    && docker-php-ext-enable xdebug \
    && apt-get clean \
    && mkdir /var/www/berlussimo

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/berlussimo

EXPOSE 9000